# Generated by Django 4.1.7 on 2023-03-31 10:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uname', models.CharField(default='Unknown', max_length=30)),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('Watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.watch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.userinfo')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
        migrations.CreateModel(
            name='MyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='india', max_length=1000)),
                ('qty', models.IntegerField(default=1)),
                ('Watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.watch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.userinfo')),
            ],
            options={
                'db_table': 'MyCard',
            },
        ),
    ]
