# Generated by Django 4.1.7 on 2023-03-31 10:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_delete_ordermaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(default=datetime.datetime.now)),
                ('amount', models.FloatField(default=10000)),
                ('details', models.CharField(max_length=1000)),
                ('address', models.CharField(default='india', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.userinfo')),
            ],
            options={
                'db_table': 'OrderMaster',
            },
        ),
    ]
