# Generated by Django 4.1.7 on 2023-04-01 17:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
        ('User', '0003_ordermaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('payment', models.CharField(blank=True, max_length=100)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('Watch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.watch')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.userinfo')),
            ],
            options={
                'db_table': 'CheckoutDetail',
            },
        ),
    ]
