# Generated by Django 4.1.7 on 2023-04-02 06:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_checkoutdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycard',
            name='address',
        ),
        
    ]
