# Generated by Django 4.1.7 on 2023-04-02 14:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
        ('User', '0005_remove_mycard_address_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivary', models.DateTimeField(default=0.005934718100890208, verbose_name=datetime.timedelta(days=5))),
                ('checkoutdetail', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='User.checkoutdetail')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.watch')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
