# Generated by Django 4.1.7 on 2023-04-02 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivary',
            field=models.DateTimeField(default='2012-10-12', verbose_name=datetime.timedelta(days=5)),
        ),
    ]
