# Generated by Django 4.1.7 on 2023-04-02 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_remove_checkoutdetail_user_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.userinfo'),
        ),
    ]
