# Generated by Django 4.1.7 on 2023-04-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_checkoutdetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermaster',
            name='address',
        ),
    ]
