# Generated by Django 4.1.7 on 2023-04-03 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_order_qty_alter_checkoutdetail_orderdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutdetail',
            name='Watch',
        ),
        migrations.RemoveField(
            model_name='checkoutdetail',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='checkoutdetail',
            name='user',
        ),
        migrations.AlterField(
            model_name='checkoutdetail',
            name='orderdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 3, 21, 42, 34, 626079)),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 3, 21, 42, 34, 626079)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 3, 21, 42, 34, 626079)),
        ),
    ]
