# Generated by Django 4.1.7 on 2023-04-04 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_alter_checkoutdetail_orderdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='uname',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='checkoutdetail',
            name='orderdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 12, 56, 6, 732278)),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 12, 56, 6, 732278)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 12, 56, 6, 732278)),
        ),
    ]
